### ISSUE TITLE
Add Images to RSS Feed

### ISSUE THREAD

**Issue by jackrugile** [tholman/inspiring-online#23]
This feature is important to me, especially with content that is a spotlight for other cool sites. If we were to do this, is there an official RSS compliant tag for an image? Or would we just add an img tag directly in the description section?

**Comment by tholman** [comment]
Oh yeah, this is a must.

I'd actually done it before, and it seemed to work. https://github.com/tholman/inspiring-online/blob/08655256c111ddac79454498179d324c20ec6bff/feed.xml ... but then I undid it, because I somehow through feedly was getting images anyway (it wasn't) ... felt strange though. The RSS format confused me.

Gotta add this back in, and I think we'd be good... or perhaps we can add the image tag in the feed.xml and it would be fine too. :/

Then again, adding the image and link into the post wouldn't hurt either.

**Comment by tholman** [comment]
Haha, that whole comment was just a brainfart. But yes. Need this!

**Comment by tholman** [comment]
Should be done! ... Lets just wait and see if it works :)
